[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "make-crl"
version = "0.1.0"
authors = [
  { name="suut", email="contact@suut.in" },
]
maintainers = [
  { name="suut", email="contact@suut.in" },
]
description = "CRL creation script"
readme = "README.md"
keywords = ["crl", "rfc5280", "x509", "pki"]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Topic :: Security :: Cryptography"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "pyasn1==0.6.4",
  "pyasn1_modules==0.4.2"
]

[project.scripts]
make-crl = "make_crl.make_crl:app"

[project.urls]
Homepage = "https://github.com/suut/make-crl"
Issues = "https://github.com/suut/make-crl/issues"
